### ISSUE TITLE
Adding weights to the detailed views

### ISSUE THREAD

**Issue by alejandravv** [q-rapids/qrapids-dashboard#106]
In detailed views (Detailed SI & Factors) visualise the evaluation value and the weighted value in charts. The user needs to see the axis weights to understand the how the elements is affecting to the computation.

**Comment by lidix91** [comment]
Implementing a new view for Detailed SI and Factors, using staked bar charts. 

![image](https://user-images.githubusercontent.com/10742203/73078128-dae0d780-3ec1-11ea-9e34-f1d4c530c056.png)

Showing the contribution of the factors to the SI.

**Comment by lidix91** [comment]
It should be better using non showing the % of each factor in SI (all bars raise until 100%), the bar chart should represent the level of quality (i.e. the assessement value), each factor should represent the weighted contribution. In the case of non-weighted SI computation % do not provide any value. 

![image](https://user-images.githubusercontent.com/10742203/73262651-ff44f880-41ce-11ea-83f1-909ac374656e.png)

**Comment by lidix91** [comment]
- Detailed SI --> one chart with all of them?
- Factors --> one chart per factor?, if the user is arribing because of navigation (from detalied SI), 1 chart per SI

Maybe it has more sense for the historical views (to be discussed)

**Comment by alejandravv** [comment]
We close this issue because we merged the corresponding branch to develop branch, but will continue making improvements for this new representation in the future.
