### ISSUE TITLE
Visualise categories in the current views

### ISSUE THREAD

**Issue by alejandravv** [q-rapids/qrapids-dashboard#107]
In the detailed views (Detailed SI & factors) add information about categories in charts. This information is already visualised in the historical views.

**Comment by lidix91** [comment]
If we use the radar with polygon chart from apexcharts? Maybe the categories could be the polygons (check if the poligons can be coloured like categories)

https://apexcharts.com/javascript-chart-demos/radar-charts/radar-with-polygon-fill/

**Comment by alejandravv** [comment]
Current chart library is Charts.js (https://www.chartjs.org/docs/latest/charts/radar.html), see section of Scale Options > Linear Radial Axis > Grid Line Configuration (https://www.chartjs.org/docs/latest/axes/styling.html#grid-line-configuration). Maybe the configurable options avalable there can help with our proposal.

**Comment by lidix91** [comment]
Problem with 1-axis charts:  **Option A: using b-axis charts for 1 and 2-axis formulas**
![image](https://user-images.githubusercontent.com/10742203/74827788-47f35b80-530e-11ea-8aec-c92a1effe6fe.png)

**Comment by lidix91** [comment]
Problem with 1-axis charts:  **Optionb Bb: using DOTSb  1-axis formulas**
![image](https://user-images.githubusercontent.com/10742203/74827883-6fe2bf00-530e-11ea-9944-2cb8135e9ea9.png)

**Comment by alejandravv** [comment]
Thanks to your likes, we finally implemented option A and we can close this issue successfully.
