### ISSUE TITLE
create default categories when the database is empty

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#117]

**Comment by lidix91** [comment]
Possibitlities:
3-category: Good (green); Fair (orange or yellow); Bad (red)
4-category: Excellent (green); Good (yellow); Poor (orange); Bad (red)
5-category: Excellent (green); Good (light green), Average (yellow); Poor (orange); Bad (red)

**Comment by prabhatram** [comment]
I suppose 3-category would be fine; simple and straightforward. Provided, the users also get the specific information like why a certain metric is good, fair, or bad. This brings us back to being able to view the exact metric value on the dashboard itself, along with the classification of that value as per the 3/4/5 category. I presume the user will be able to dictate beyond what value a metric should be termed good, fair, bad.

**Comment by alejandravv** [comment]
Between several possibilities, finally we decide to use 3-category: Good (green); Normal (orange); Bad (red). We chose Normal as a central value because it's a neutral label for this case, and we think that Fair has a little bit negative meaning.
