### ISSUE TITLE
Enhance prediction views

### ISSUE THREAD

**Issue by martimanzano** [q-rapids/qrapids-dashboard#130]
For the individual elements' prediction view, it would be nice to improve the plots, including part of the past element's historical data and confidence intervals. 

Something like:

![image](https://user-images.githubusercontent.com/7520973/74939315-f58a6b80-53ef-11ea-9a10-4d703e7e11d8.png)

**Comment by alejandravv** [comment]
Helpful link that explain how it can be painted a region on a line chart with fill option. 
https://www.chartjs.org/samples/latest/charts/area/line-datasets.html
May be we can use it to represent the intervals of confidence.

**Comment by alejandravv** [comment]
We decide to show historical data and intervals of confidence to SI prediction views and Metrics prediction.  
In case of Detailed SI and Factors prediction views, we are sure that we won't show intervals of confidence, but will we show historical data for this views?

**Comment by lidix91** [comment]
We need to include also de historical data, same logic as the other views
