### ISSUE TITLE
Consult Quality Factors [US_2]

### ISSUE THREAD

**Issue by alejandravv** [q-rapids/qrapids-dashboard#137]
- [x] Make and show an ordered list of all quality factors of the system (by project)
- [x] Get single quality factor information from database
- [x] Show quality factor information

**Comment by lidix91** [comment]
The factors should be created by project, like SIs. So, the list should be filtered by project (like SIs)

**Comment by alejandravv** [comment]
factors_management branch was merged to develop branch
