### ISSUE TITLE
add a trend line in Historical Data Views

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#146]

**Comment by lidix91** [comment]
https://github.com/Makanz/chartjs-plugin-trendline

**Comment by alejandravv** [comment]
In our case we have time series to show historical data on line charts, but it seems that it's not supported in this version of plugin. 

I found en implemented solution in one of [issue](https://github.com/Makanz/chartjs-plugin-trendline/issues/10) responses: https://github.com/SigloTech/chartjs-plugin-trendline
