### ISSUE TITLE
Customise visualization depending on the user role/group

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#147]
customisation for each user role/group:
- [x] all/concrete projects
- [x] all/concrete strategic indicators
- [x] all/concrete level (only metrics, metrics& factors, all)

**Comment by lidix91** [comment]
related to issue #5

**Comment by lidix91** [comment]
level of customisation:
- [ ] all/concrete projects
- [ ] all/concrete strategic indicators

**Comment by alejandravv** [comment]
merged to develop
