### ISSUE TITLE
assessSI from a concrete date does not work

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#156]

**Comment by alejandravv** [comment]
When the date "from" parameter is specified, the dashboard tries to look for the historical metrics of that day, if there are no values, it cannot do the factor assessment. The same thing in going on for the case of strategic indicators.

To correct this behavior, when this case is taken, we can take the last values calculated of metrics or factors and proceed with factor or strategic indicators assessment.
