### ISSUE TITLE
Error in the factors simulation view ("infinity" label)

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#170]
In a case with 3 factors, with very low values (0.35, 0, 0)

![image](https://user-images.githubusercontent.com/10742203/93780981-20100180-fc29-11ea-8a1e-2c85f4204a1f.png)

If I increase one of the 0 factors (e.g., the second), then a "infinity" label appear in the increasement area, instead of a number

![image](https://user-images.githubusercontent.com/10742203/93780873-fd7de880-fc28-11ea-8631-22a5d14c567e.png)

**Comment by alejandravv** [comment]
Corrected on feature/newVisualizationForDetailedViews branch
