### ISSUE TITLE
Rationale for metrics is hard to understand

### ISSUE THREAD

**Issue by XavierFranch** [q-rapids/qrapids-dashboard#196]
First, I'm not sure that "rationale" is the best possible name. Second, I wonder who is the stakeholder that should read this "rationale". The way it is shown is very technical and low level, and can be not easy to understand

**Comment by lidix91** [comment]
The rationale includes technical more technical details for metrics, metrics are more addressed to lower-level stakeholders (developers, server technicians,..). For factors and strategic indicators are more high-level description, these kind of incators are addressed to more high-level stakeholders (project manager, quality assurance engineer, product owner,...) , but maybe not enough. 

For strategic indicators indicates the list of factors and if it is applied an average or weighted average. An analog description for factors.

**Comment by alejandravv** [comment]
Finally we decided that it would be better to replace the name "rational" with "technical details" so as not to confuse users.
