### ISSUE TITLE
Add a hierarchical quality model view in the assessment option

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#21]
We need a view where the elements are shown in a hierarchical way. Strategic Indicators linked to the Factors impacting on them, and factors linked to the Metrics used to computed them.

This view should include the current assessment of the elements and the weights in the links to make explicit the importance of each element in the computation of the one just avobe.

- [x] Materialise the strategic indicators computation in the relation.XXX index in elastic
- [x] The view should use index relation.XXX as a source for the visualization

**Comment by lidix91** [comment]
This task needs the new version of qrapids-qma-elastic (v0.11)

**Comment by AleixBalletbo** [comment]
Tasks:

- [ ] Write relations SI -> factor
- [ ] Read all relations
- [ ] Build and show graph
- [ ] Show details for each element

Estimated effort = 40 hours

**Comment by AleixBalletbo** [comment]
Final effort: 50 hours
