### ISSUE TITLE
Add simulation at level of metrics

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#22]
The form should be similar to the simulation at level of factors, the user should be able to set up values for the metrics, and visualize the impact on factors (using radar charts) and strategic indicators (using gauge charts)

**Comment by lidix91** [comment]
depending of qrapids-qma-elastic issue number 3

**Comment by AleixBalletbo** [comment]
Estimated effort: 20 hours

Final effort: 19 hours
