### ISSUE TITLE
Add simulation for the generated QRs

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#23]
The form needs to include the generated QR information and the user should be able to simulate the values for the different params included in the QR and take the decision of including or not including the concret QR (QR pattern + concrete values for the parameters)

**Comment by lidix91** [comment]
depending of qrapids-qma-elastic issue number 3

**Comment by AleixBalletbo** [comment]
Estimated effort: 20 hours

Final effort: 18 hours
