### ISSUE TITLE
Add simulation for QR using the QR pattern catalogue

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#24]
The user should be able to select a QR pattern from the catalogue, simulate values for the params and decide to include the concret QR (QR pattern + concrete values for the parameters)

**Comment by lidix91** [comment]
depending of qrapids-qma-elastic issue number 3
related to issue  #23

**Comment by AleixBalletbo** [comment]
Estimated effort: 15 hours
Real effort: 12 hours
