### ISSUE TITLE
QR button is not shown for the alerts

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#27]
In the alerts form, there is no button to generate QR

**Comment by marcoriol** [comment]
fixed in the qrapids_qr-generator module

**Comment by lidix91** [comment]
Is this issue closed because the new version of the qr_generation is already integrated in the dashboard?

**Comment by AleixBalletbo** [comment]
Yes, the integration is done here (2dcf92bef842c3b66501a8e35159072ba208e1da)
