### ISSUE TITLE
Quality Model View does not show the elements consistently

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#32]
We have assessment for strategic indicators, factors and metrics (relations stored in relation index) but the Quality Model view only show the relation betwen strategic indicators and factors, but is not showing the relation between factors and metrics.

**Comment by martimanzano** [comment]
I'm not able to reproduce the issue. I can see the complete hierarchy either on the QMA and the dashboard.

**Comment by lidix91** [comment]
With the current content in the relation index cannot be fix it.
