### ISSUE TITLE
Documentation - Packaging Inconsistency 

### ISSUE THREAD

**Issue by aabherve** [q-rapids/qrapids-dashboard#39]
The deployment documentation indicate that the packaging should contained the TimeSeriesFunctions script (https://github.com/q-rapids/qrapids-dashboard/wiki/How-to-deploy-the-Strategic-Dashboard)

It 's not the case in the qrapids-dashboard v0.3.2 release

**Comment by martimanzano** [comment]
We are currently addressing this issue taking into account the license restrictions.

The deployment package of the next versions will bundle a timeseriesfunctions script containing a subset of the implemented forecasting methods respecting the q-rapids aimed license.

The script containing the complete set of forecasting methods is already available in a [separate repository](https://github.com/q-rapids/qrapids-forecast-R_script) with its corresponding license.

**Comment by lidix91** [comment]
@aabherve, is this issue fixed with the current documentation and intallation package (v. 0.3.3)

**Comment by aabherve** [comment]
Fixed in the package  0.3.3
