### ISSUE TITLE
Quality requirements with project_id and decision_rationale

### ISSUE THREAD

**Issue by marcoriol** [q-rapids/qrapids-dashboard#46]
We need to add the project_id and decision_rationale fields in the JSON of a new quality requirement to be inserted into the backlog. The JSON file will look like this (new fields in bold): 

{
        "issue_summary":"Ratio of fast unit tests should be at least 70%”,
        "issue_description":"Ratio of fast unit tests (i.e. Unit tests that takes less than 5 minutes to execute) with respect to the total number of unit tests should         be at least the given value in order to improve the testing status of the software system.”,
        "issue_type":”Story",
       **"project_id": "Your backlog project ID (if it is set in the Q-Rapids Dashboard)",
       "decision_rationale": "The rationale of the decision"**
}

**Comment by lidix91** [comment]
@AleixBalletbo we need a new attribute in the table "project" to indicate the project id in the backlog tool (alphanumeric) --> new attribute in the table and new field in the project form
