### ISSUE TITLE
Dashboard historical visualisation (HistoricChart) fails to display the information box inside the chart completely.

### ISSUE THREAD

**Issue by japjoops** [q-rapids/qrapids-dashboard#53]
When the overlay is used, the overlaying display box does not always locate itself inside the field,
which is used in displaying the metric. The box is drawn either completely or partly. 
The issue exists with every line or limits only to one line inside the chart. 
The current view does not have the issue by reporter's knowledge. If the current view has the issue,
this issue should be edited. 

Edited picture of the issue as an attachment. 

Estimation: max 2h

![historical_chart_bug_grayscale](https://user-images.githubusercontent.com/50356409/57694193-c0c4d900-7653-11e9-8fe7-1035c9bb9d74.png)

**Comment by lidix91** [comment]
Is this problesm happening only for charts with "a lot of" series? in the image, there are 9 series.

The space for each chart is fixed, we could remove the legend when there are more than X series.

**Comment by japjoops** [comment]
The bug seems to relate to location of the dot. The number of series does not seem to be the reason (e.g. chart with only 5 series, displays the box erroneously). The problem seems to be that the box does not locate itself with positional information even though the display box would fit to the reserved space. For example dots 1-4 would display properly while dots 5-7 would not - the reason being that the connection point of the box is fixed to the data point.
